### ISSUE TITLE
Gherkin Unit testing

### ISSUE THREAD

**Issue by luis-ffe** [SEAME-pt/Team02-WarmUp#35]
# Description

- Research Gherkin
- Try it setup some tests
- Use it in the repository to unit testing
- Try to run in in the self hosted machine with tests

**Comment by Rui-Pedro-Pires** [comment]
We did some research and after understanding a little more about it, and seeing that for c++ it actualy uses another frameworks to implement the tests, as Google Tests, we decided to start by implementing tests with google tests and open a new issue to keep researching for the future projects like the cluster one, that will have more UI tests.
