### ISSUE TITLE
Misra / codeQL learn how to use.

### ISSUE THREAD

**Issue by luis-ffe** [SEAME-pt/Team02-WarmUp#37]
# Story 

- SEAME-pt/Team02-Cluster#14 

## Description

- research Misra Guidelines and c++ good practices for safety critical protocol.
- set codeQl to check our code as others do in their repos.
- set repository folder structure with Guidelines and other stuff.

**Comment by mjorgecruz** [comment]
This task entailed getting knowledge on MISRA guidelines.


Two workflows were created in the main repository to access the implementation of MISRA guidelines. Tests need to be passed to allow the pull request to be merged.
