### ISSUE TITLE
Learn Qt Design Studio

### ISSUE THREAD

**Issue by mjorgecruz** [SEAME-pt/Team02-WarmUp#47]
# Description

After spending sometime on the Qt  widget designer, the software we are going to use in the course is the Qt Design Studio. Therefore, it makes sense to consider spending a few days learning about Qt Design Studio.

**Comment by Rui-Pedro-Pires** [comment]
After some research we found out that it would be better to use the widget designer to create the ui for the RaceTrack.
With that we decided to close this issue as not planned, and to create a new issue to learn more about the QT Design Studio in a next sprint, for the next project ( Cluster ).
