### ISSUE TITLE
[Task]  Template Organization

### ISSUE THREAD

**Issue by ziliolu** [SEAME-pt/Team02-WarmUp#69]
### Title

Template Organization

### Description

Better organization for the issue templates for all repos

### Priority

High

**Comment by ziliolu** [comment]
Templates for issues working now as expected. Current available options: Task, Epic, Story and Bug templates.  

https://github.com/SEAME-pt/Team02-Template/tree/main/.github/ISSUE_TEMPLATE

**Comment by Rui-Pedro-Pires** [comment]
> Templates for issues working now as expected. Current available options: Task, Epic, Story and Bug templates.
> 
> https://github.com/SEAME-pt/Team02-Template/tree/main/.github/ISSUE_TEMPLATE
